### ISSUE TITLE
Roadmap to v2

### ISSUE THREAD

**Issue by fujiwara** [kayac/ecspresso#374]
- [x] Switch to aws-sdk-go-v2.
- [x] rollback --deregister-task-definition true by default.
   - Raise an error when rollback --deregister-task-definition with --no-wait.
- [x] #344 
  - [x] #449 
- [ ] #45
- [x] Abolish create subcommand. use deploy subcommand simply.
  https://github.com/kayac/ecspresso/pull/435
- [ ] No require `service_definition` if run tasks only.
- [x] render command accepts render target by CLI args instead of flags (e.g. --task-definition)
  https://github.com/kayac/ecspresso/pull/444
- [x] Remove fallback to executionRole.
  https://github.com/kayac/ecspresso/pull/269
- [x] diff --unified by default.
- [x] init --jsonnet by default.
  https://github.com/kayac/ecspresso/pull/447
- [x] Progress bar for codedeploy #412
- [x] Switch CLI parser from kingpin.
  #455 

...and so on

**Comment by cohalz** [comment]
I've prepared some proposals, but are there any that you like?

- Remove fallback to executionRole.
  - refs #269
- `diff --unified` by default.
- `init --jsonnet` by default.
- Change config file to jsonnet instead of yaml.
  - In short, it ’s all going to be jsonnet.

**Comment by fujiwara** [comment]
- [x] #380 
- [x] Switch a logger to fujiwara/logutils or etc.

**Comment by fujiwara** [comment]
Now, the pre-v2 branch created!

**Comment by fujiwara** [comment]
[v2.0.0](https://github.com/kayac/ecspresso/releases/tag/v2.0.0) released!
